version: '3.7'
services:
  nginx: 
    image: revard/nginx-alpine-php:1.0
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - "./www:/var/www"
      - "./logs:/var/log/nginx"
    networks:
      web_net:
    links:
      - php
  php:
    image: revard/php-nginx:1.0
    ports:
      - "9000:9000"
    volumes:
      - "./www:/var/www"
    networks:
      web_net:
networks:
  web_net: