# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
  
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "ansible/playbook.yml"
      ansible.become= "true"
    end
  
  
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
    end
  
    config.vm.define "master" do |master|
      master.vm.network "private_network", ip: "192.168.100.10", virtualbox__intnet: "net"
      master.vm.hostname = "master"
    end
  
    config.vm.define "slave" do |slave|
      slave.vm.network "private_network", ip: "192.168.100.11", virtualbox__intnet: "net"
      slave.vm.hostname = "slave"
    end
  
    config.vm.define "backup" do |backup|
      backup.vm.network "private_network", ip: "192.168.100.12", virtualbox__intnet: "net"
      backup.vm.hostname = "backup"
    end
  
  end