Vagrant.configure(2) do |config|

  config.vm.define "log" do |subconfig|
    subconfig.vm.box = "ubuntu/xenial64"
    subconfig.vm.hostname="log"
    subconfig.vm.network :private_network, ip: "192.168.50.11"
    subconfig.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "2"
    end
  end

  config.vm.define "web" do |subconfig|
    subconfig.vm.box = "ubuntu/xenial64"
    subconfig.vm.hostname="web"
    subconfig.vm.network :private_network, ip: "192.168.50.12"
    subconfig.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end


  config.ssh.insert_key = false 
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"  

  config.vm.provision "shell", inline: <<-SHELL
  if [ ! -f "/usr/bin/python" -a -f "/usr/bin/python3" ]; then ln -s /usr/bin/python3 /usr/bin/python; fi
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
  end

end