# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  :docker => {
        :box_name => "centos/7",  
        #:box_name => "sgaunet/c7ansdoc",
#        :ip_addr => '192.168.1.150',
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "public_network", ip: "192.168.1.150"
          #box.vm.network "public_network", use_dhcp_assigned_default_route: true

          box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "4096"]
          vb.customize ["modifyvm", :id, "--cpus", "4"]
          vb.name = boxname.to_s

          end
     

      case boxname.to_s
      when "docker"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          yum install epel-release -y
          yum install docker vim -y
          yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo -y
          yum install docker-ce docker-ce-cli containerd.io -y
          systemctl start docker
          usermod -aG docker vagrant
          curl -L https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
          chmod 664 /var/run/docker.sock
          chmod 777 /var/run/docker.sock
          mkdir ~/dcompose
          cp -R /vagrant/dcompose/ /home/vagrant/
          cd /vagrant/dcompose/
          docker-compose up --build -d
          SHELL
          #config.vm.provision "shell", path: "./provision.sh"
      end

      end
   end
end