---
# tasks file for postfix

- name: install postfix
  yum:
    name: postfix
    state: present
  notify: restart postfix

- name: install mail client
  yum:
    name: mailx
    state: present

- name: copy ready postfix config file
  template:
    src: templates/main.cf
    dest: /etc/postfix/main.cf
  notify: restart postfix