# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.box_check_update = false
  
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision/main.yml"
      ansible.verbose = "v"
    end
  
    config.vm.define "server" do |server|
      server.vm.hostname = "server.test.local"
      server.vm.network "private_network", ip: "192.168.101.1"
      server.vm.network "forwarded_port", guest: 25, host: 8025
      server.vm.network "forwarded_port", guest: 143, host: 8143
    end
  
  end