# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "./playbook.yml"
      ansible.become = "true"
    end
  
  
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
    end
  
    config.vm.define "webserver" do |webserver|
      webserver.vm.network "public_network", ip: "192.168.1.100"
      webserver.vm.hostname = "webserver"
    end
  
  end