Vagrant.configure(2) do |config|

    config.vm.define "ipaserver" do |subconfig|
      subconfig.vm.box = "centos/7"  
      subconfig.vm.hostname="ipaserver.test.local"
      subconfig.vm.network :private_network, ip: "192.168.50.41"
      subconfig.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = "2"
      end
#      config.vm.provision "shell", inline: <<-SHELL
#        yum install -y firewalld
#        systemctl start firewalld
#        systemctl status firewalld
#        echo "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4" > /etc/hosts
#        echo "192.168.50.41 ipaserver.test.local ipaserver" >> /etc/hosts
#        SHELL
      config.vm.provision "ansible" do |ansible|
        ansible.inventory_path = "./hosts"
#        ansible.verbose = "v"
        ansible.playbook = "ipaserver.yml"
      end
      
    end
  
    config.vm.define "ipaclient" do |subconfig|
      subconfig.vm.box = "centos/7"
      subconfig.vm.hostname="ipaclient.test.local"
      subconfig.vm.network :private_network, ip: "192.168.50.42"
      subconfig.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = "2"
      end
#      config.vm.provision "shell", inline: <<-SHELL
#      echo "Be patient waiting 60 sec while ipa server goes up." 
#       sleep 60
#      echo "192.168.50.41 ipaserver.test.local ipaserver" >> /etc/hosts
#        SHELL
      config.vm.provision "ansible" do |ansible|
        ansible.inventory_path = "./hosts"
#        ansible.verbose = "v"
        ansible.playbook = "ipaclient.yml"
      end
      
    end
  
  
    config.ssh.insert_key = false 
    config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"  
  
    config.vm.provision "shell", inline: <<-SHELL
    if [ ! -f "/usr/bin/python" -a -f "/usr/bin/python3" ]; then ln -s /usr/bin/python3 /usr/bin/python; fi
    SHELL
  
  end